global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://copime.org.ar
          - https://cancilleria.gob.ar
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Debe coincidir con el nombre del servicio del Blackbox Exporter

rule_files:
  - "alert.rules.yml"  # Asegúrate de que este archivo exista y tenga las reglas de alerta

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'  # Dirección del Alertmanager
